build:
	latexmk -pdf -output-directory=_build УИТПиИМ_ПО-4_Галанин_лаб1.tex
	latexmk -pdf -output-directory=_build УИТПиИМ_ПО-4_Галанин_лаб2.tex
	latexmk -pdf -output-directory=_build УИТПиИМ_ПО-4_Галанин_лаб3.tex
	latexmk -pdf -output-directory=_build УИТПиИМ_ПО-4_Галанин_лаб4.tex
	latexmk -pdf -output-directory=_build УИТПиИМ_ПО-4_Галанин_лаб5.tex

clean:
	rm -rfv ./*/*.aux
	rm -rfv ./*/*.fdb_latexmk
	rm -rfv ./*/*.fls
	rm -rfv ./*/*.log
	rm -rfv ./*/*.out
	rm -rfv ./*/*.pdf
	rm -rfv ./*/*.synctex.gz
	rm -rfv ./*/*.toc
