version: "3"
services:
  latex:
    image: mirisbowring/texlive_ctan_full:2019
    volumes:
      - ./:/app/
      - ./docker/build/:/build/
      - ./docker/temp/:/temp/
    command: make -C /app/report docker-compose-script
